services:
  linkedink:
    build: .
    container_name: linkedink
    restart: always
    ports:
      - "3006:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      # Updated the hostname from 'db' to 'linkedink-db'
      - DATABASE_URL=postgresql://postgres:postgres@linkedink-db:5432/linkedink
      - QDRANT_URL=http://qdrant:6333
      - NEXTAUTH_URL=https://portfolio.sarthakpm.online/Linkedink
    depends_on:
      - linkedink-db
      - qdrant
    networks:
      - n8n-docker_default

  linkedink-db:
    image: postgres:16-alpine
    container_name: linkedink-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=linkedink
    volumes:
      - linkedink_db_data:/var/lib/postgresql/data
    networks:
      - n8n-docker_default

  qdrant:
    image: qdrant/qdrant:latest
    container_name: linkedink-qdrant
    restart: always
    volumes:
      - linkedink_qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - n8n-docker_default

volumes:
  linkedink_db_data:
  linkedink_qdrant_data:


networks:
  n8n-docker_default:
    external: true
